name: Lint

on:
  push:
    branches:
      - '*'  # Runs on all branches

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'  # Specify the Go version

      - name: Install dependencies
        working-directory: ./ozon-product-requester  # Set working directory
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: v1.64.6  # Specify the golangci-lint version
          working-directory: ./ozon-product-requester  # Set working directory

      - name: Lint
        working-directory: ./ozon-product-requester  # Set working directory
        run: golangci-lint run  # Run the linter